version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/kaumnen/cipr/cmd.version={{.Version}}

universal_binaries:
  - replace: true

release:
  github:
    owner: kaumnen
    name: cipr

brews:
  - homepage: https://github.com/kaumnen/homebrew-tap
    repository:
      owner: kaumnen
      name: homebrew-tap

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
