version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    goamd64:
      - v2
      - v3

universal_binaries:
  - replace: true

release:
  github:
    owner: kaumnen
    name: cipr

brews:
  - homepage: https://github.com/kaumnen/homebrew-kaumnen
    repository:
      owner: kaumnen
      name: homebrew-kaumnen

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
